### ISSUE TITLE
filter is replacing "." with "_" in query

### ISSUE THREAD

**Issue by salzamt** [marcelgwerder/laravel-api-handler#12]
hi, thanks for this awesome plugin!
I am using https://github.com/jenssegers/laravel-mongodb for mongodb support in laravel.
when I use the query string "?lang.en_US.status=confirmed" it is converted to "lang_en_US_status":"confirmed" in the query string. 
any idea why?
cheers riccardo

**Comment by marcelgwerder** [comment]
Hey
I can't really see a relation to my package here but I guess you are referring to that problem:
[Get PHP to stop replacing '.' characters in $_GET or $_POST arrays?](http://stackoverflow.com/a/68742/983992)

**Comment by salzamt** [comment]
oh man thats right, thank you!
my first guess was that this plugin expects mysql syntax and therefore converts it to _ ^^
sorry for that
