### ISSUE TITLE
Envelope/Headers

### ISSUE THREAD

**Issue by webkenny** [marcelgwerder/laravel-api-handler#19]
In the `README` it says that two custom headers will be returned indicating total and filter count or, if you prefer, you could include them in the body with a configuration variable. So far, neither of these seem to be working. FWIW, it doesn't appear in the `config/api.php` file that there is a variable for envelope anyway.

Here's an example piece of code that returns a JSON object via my Fractal transformer:

```
// API Handler Call
$campaigns = ApiHandler::parseMultiple(new Campaign, Campaign::getSearchedFields(), $request->all())->getBuilder();

// Simple Scope to Keep Records to the Account Calling
$response = $campaigns->inAccount($this->account, $this->user, $request->get('user_id'), null !== $request->input('me'))->get();

// Provided by Dingo API package but is basically just a helper for sending back JSON.
return $this->response()->collection($response, new CampaignTransformer);
```

Here's the headers I get back:

```
Cache-Control → no-cache
Connection → keep-alive
Content-Type → application/json
Date → Fri, 23 Oct 2015 15:00:08 GMT
Server → nginx/1.8.0
Transfer-Encoding → chunked
```

And note that nothing appears in the response body even if I pass the `_config` param explicitly.

Am I missing something? Thanks so much for a fantastic package, Marcel. Much appreciated sir!

**Comment by marcelgwerder** [comment]
I'm not aware of this issue, thx for reporting it. I will definitely look into it. I'm pretty busy right now though and I almost certainly won't be able to do this in the next few weeks.

**Comment by od3n** [comment]
@webkenny are you changing the correct config file? it should be `config/apihandler.php`

change `'envelope' => false,` to `envelope' => true,`

and don't forget to include `_config=meta-total-count,meta-filter-count` query string to your api request

`http://api.example.dev/users?config=meta-total-count,meta-filter-count`

**Comment by marcelgwerder** [comment]
Never heard of the issue again and could not reproduce myself. If there is still an issue, it will probably be gone in v1.0 anyway.
