### ISSUE TITLE
Predefined filter partially not working ?

### ISSUE THREAD

**Issue by baumelt** [marcelgwerder/laravel-api-handler#24]
Hey there.
I'm new to Laravel (5.1) and the whole plugin stuff and would appreciate a little help. :)

Following the instructions i got the ApiHandler to work with regular parameters and its awesome, but some of the predefined functions throw sql erros since they seem to be interpreted as table columns.

Specifically `_sort`, `_fields` and `_with` don't seem to work, while  `_offset`, `_limit` and `_q` for example work as intended.
I didn't change anything in the `config/apihandler.php`, prefix is still '_' and i added `@Relation` annotations to the needed relation as described. Do i have to register these params anywhere?

Error when using sort: `/api/posts?_sort=name`

```
QueryException in Connection.php line 664:
SQLSTATE[42S22]: Column not found: Unknown column '_sort' in 'where clause' (SQL: select * from `posts` where `posts`.`deleted_at` is null and `_sort` = name order by `name` asc)
```

Error when using with: `/api/posts?_with=user`

```
QueryException in Connection.php line 664:
SQLSTATE[42S22]: Column not found: Unknown column '_with' in 'where clause' (SQL: select * from `posts` where `posts`.`deleted_at` is null and `_with` = user)
```

Any ideas what i am missing, or where to look for the source of failure would be highly appreciated! :)

**Comment by marcelgwerder** [comment]
There is no need to do anything more. Looks like somehow `_sort` and `_with` are not detected as predefined parameters. I used this code with many Laravel versions including 5.1 and never had such issues.

Can you post the code where you call the handler and the PHP version you're using?

**Comment by baumelt** [comment]
Hey Marcel,

thank you for the quick reply. Sadly i still haven't figured out what is causing the failure
.

The Php Version that came with my vagrant seems to be PHP 7.0.5. Maybe that causes the issue?

Here are the relevant code snippets:

**Post Controller:**
```
public function index(Request $request) {

        // find all posts with selected nested relations
        $posts = Post::with('address');

        // remove unwanted params from request
        $searchParams = $request->except(['token']);

        $searchable = ['id', 'name', 'latitude', 'longitude'];

        try {

            // apply optional search query parameters as filter and return result
            return \ApiHandler::parseMultiple($posts, $searchable, $searchParams)->getResponse();

        } catch (Exception $e) {/*...*/}
    }
```


**Post Model**:
```
    /**
     * @Relation
     */
    public function address() {
        return $this->belongsTo(Address::class);
    }

    /**
     * @Relation
     */
    public function user() {
        return $this->belongsTo(User::class);
    }
```

**When calling `/api/posts?_with=user`**:

```
SQLSTATE[42S22]: Column not found: Unknown column '_with' in 'where clause' (SQL: select * from `posts` where `posts`.`deleted_at` is null and `_with` = user)
```

Im still kind of confused how most of the other _parameter work nicely. But maybe you get an idea with these snippets?

**Comment by marcelgwerder** [comment]
Hmm I can't see an issue on the first glimpse. But I didn't really test the library against PHP 7 yet so It is possible that there is some different behaviour. Is it possible for you to test your code on PHP 5.6 without too much hassle?

**Comment by baumelt** [comment]
Just testet everything with PHP v5.6, but the errors remained the same; the resulting sql query always treats the params as attributes.

I then tried to debug the APIHandler and was able to isolate the issue to the `Parser->getFilterParams()` Function. 
At least for me the `array_diff_ukey` in Line 277 doesn't return a correct array of filter params for some reason i can't get my head around yet...

`Parser.php - Line 272-286:`
```
    protected function getFilterParams()
    {
        $reserved = array_fill_keys($this->functions, true);
        $prefix = $this->prefix;
        $filterParams = array_diff_ukey($this->params, $reserved, function ($a, $b) use ($prefix) {
            return $a != $prefix . $b;
        });
        if (count($filterParams) > 0) {
            return $filterParams;
        }
        return false;
    }
```

---

For Example when provided with `_limit`the key will be removed from $this->params but the `_sort` key won't. It seems the function is not comparing all pairs of keys provided correctly.

To ckek this i added a simple `echo` output to the compare callback function as below:

```
        $filterParams = array_diff_ukey($this->params, $reserved, function ($a, $b) use ($prefix) {
            echo("\$a:" . $a . " != \$b:" . $prefix . $b . " | " . (($a != $prefix . $b) ? 'true' : 'FALSE') . "<br/>");
            return $a != $prefix . $b;
        });
```

Fot the request: `/api/users?_limit=1&_with=roles&_sort=name&email-lk=*com`
the output shows:
```
$a:offset != $b:_sort | true
$a:offset != $b:_limit | true
$a:offset != $b:_fields | true
$a:offset != $b:_config | true
$a:offset != $b:_with | true
$a:q != $b:_offset | true
$a:limit != $b:_sort | true
$a:limit != $b:_with | true
$a:limit != $b:_fields | true
$a:config != $b:_limit | true
$a:sort != $b:_fields | true
$a:with != $b:_sort | true
$a:_limit != $b:_limit | FALSE
$a:_with != $b:_limit | true
$a:_with != $b:_offset | true
$a:_with != $b:_q | true
$a:_sort != $b:_limit | true
$a:_sort != $b:_offset | true
$a:_sort != $b:_q | true
$a:email-lk != $b:_limit | true
$a:email-lk != $b:_offset | true
$a:email-lk != $b:_q | true
```
As you can see the _offset gets successfully removed, while the rest aren't compared to all predefined params and therefore will be passed on as filters resulting in my previous sql errors.
However, i can't believe or explain how i'm the only one having this issue and i've no idea how so :(

---

To make this work i then also tried the `array_diff_key` function to replace the `ukey` like so:

```
    protected function getFilterParams() {
        
        &_functions = ['_fields', '_sort', '_limit', '_offset', '_config', '_with', '_q']
        $reserved = array_fill_keys(_functions, true);

        $prefix = $this->prefix;

        $filterParams = array_diff_key($this->params, $reserved);

        if (count($filterParams) > 0) {
            return $filterParams;
        }

        return false;
    }
```

.. and then `_sort`and `_fields` instantly work as intended!
When using `_with` it now also gets recognized as predefined function, however there seems to be another issue with the select syntax of a query (like below), which i haven't figured out yet.
Any ideas where to look for this issue?

```
SQLSTATE[42000]: Syntax error or access violation: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '*, `users`.`id` from `users` where `users`.`deleted_at` is null' at line 1 
(SQL: select *, *, `users`.`id` from `users` where `users`.`deleted_at` is null)
```

But hey, thats at least some progress, right? :D' 

I'm kind of confused what might be wrong with my php environment, since i tried this with clean laravel/homestead vagrant boxes, version 0.3.3 and 0.4.4.
but maybe this will at least be of some future help for someone having similar problems.

**Comment by marcelgwerder** [comment]
I'll check this out and will try to reproduce it as soon as I can, thanks for investigating.

**Comment by marcelgwerder** [comment]
Using the handler with many PHP 7+ versions, I cannot reproduce. If there is still a problem, the next major version will probably make it go away anyway.
