### ISSUE TITLE
Why parseSingle

### ISSUE THREAD

**Issue by isometriq** [marcelgwerder/laravel-api-handler#27]
The "parseMultiple" method makes much sense to me with filters, offset, limit, etc...

On the other hand, the "parseSingle" method seems more accessory. Yes, it makes a simpler response code in many scenarios. I was wondering what kind of uses where it would shine.

The only thing I've found was to detect if the id is a number or text and finding in the appropriate field. ie:
```
/api/users/1  (by id)
/api/users/Administrator  (by name)
```
```
class UsersController extends RestfulController
{
    public function show(Request $request, $id)
    {
        return ApiHandler::parseSingle(User::query(), is_numeric($id) ? $id : array('name'=>$id))->getResponse();
    }
}
```

**Comment by isometriq** [comment]
Ok I think I the main point, it's the "_with" param to get a particular relationship and the "_fields" to select which fields to include:
`/api/users/2?_with=type&_fields=name,email`

The filters, sorting and limit are not applied. That expected.

**Comment by marcelgwerder** [comment]
Yep, to  limit the fields and include related objects.
