### ISSUE TITLE
Non-static method Marcelgwerder\\ApiHandler\\ApiHandler::parseMultiple() should not be called statically

### ISSUE THREAD

**Issue by Xiongzhenyu** [marcelgwerder/laravel-api-handler#43]
ApiHandler class parseSingle and parseMultiple is not static , 
so can't use ApiHandler::parseMultiple

**Comment by marcelgwerder** [comment]
My guess is that you use the class the wrong way. You should either use the facade `Marcelgwerder\ApiHandler\Facades\ApiHandler` "statically" or inject  the class `Marcelgwerder\ApiHandler\Facades\ApiHandler` in a class that supports dependency injection.

**Comment by Xiongzhenyu** [comment]
Yes, i use Marcelgwerder\ApiHandler\ApiHandler.
i fix then, is true now
