### ISSUE TITLE
[question] Use library with repository

### ISSUE THREAD

**Issue by mgralikowski** [marcelgwerder/laravel-api-handler#47]
Hello,

Has anyone tried use this library with Repository Pattern in one moment?
I use https://github.com/andersao/l5-repository and i would still use it. 

For example i have method:
$this->myRepository->getItemsByUser($loggedInApi);
And now i would to add queries to this method in my api.
Is it possible? I am not sure how can i inject QB to api-handler or another side - get QB from my repository and inject to parseMultiple().

**Comment by mgralikowski** [comment]
I think i have this!

```
      return $this->myRepository->scopeQuery(function($query) {
            return ApiHandler::parseMultiple($query)->getBuilder();
        })->getBySomethingAndOtherLogic($someValue);
```

Method getBuilder() save my day.

**Comment by marcelgwerder** [comment]
Cool you figured it out.
