### ISSUE TITLE
How can i use custom get param

### ISSUE THREAD

**Issue by mgralikowski** [marcelgwerder/laravel-api-handler#49]
I have simply index() method to get all resources but i would to use custom filter for example:

> 
/books?category=type

But category is not a column name, but just my custom attribute to use in if/else.

`if ($category) etc...`

Library is taking category and use it in WHERE condition so it is causing SQL error. I tried with _category too but same result.

Thanks.

**Comment by marcelgwerder** [comment]
The third parameter of parseMultiple takes the params. If you want to exclude one, you can do something like:

```php
ApiHandler::parseMultiple($builder, [], $request->except('category'));
```

**Comment by mgralikowski** [comment]
I can use before my method (repository method):

`$request->query->remove('category');`

but is is there any cleaner method in api ;)

**Comment by mgralikowski** [comment]
Yes, your solution works too and it's much cleaner ;)

I tried before your answer with this parameter but docs say "A list of query parameter" so i thought that i need list and write all queries names like _with, _filter etc.. to not lost library functionality.
